// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundContainerSetDataPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundContainerSetDataPacket, {
		windowId: Codecs.varInt,
		property: Codecs.short,
		value: Codecs.short,
	});

	constructor(
		public windowId: number,
		public property: number,
		public value: number
	) {
		super();
	}
}