// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

const MAX_DETAIL_COUNT = 32
const detailMapCodec = Codecs.boundedMap(Codecs.string(128), Codecs.string(4096), MAX_DETAIL_COUNT)

export class ClientboundCustomReportDetailsPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundCustomReportDetailsPacket, {
		details: detailMapCodec,
	});

	constructor(
		public details: Map<string, string>,
	) {
		super();
	}
}
