// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export enum DebugSampleType {
	TickTime = 0,
}

export class ClientboundDebugSamplePacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundDebugSamplePacket, {
		sample: Codecs.array(Codecs.long),
		sampleType: Codecs.varIntEnum(DebugSampleType),
	});

	constructor(
		public sample: bigint[],
		public sampleType: DebugSampleType
	) {
		super();
	}
}