// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { DebugSubscription } from '@dripleaf/registry';
import { codec, Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export type DebugEventPayload = {
	subscription: DebugSubscription
	payload: Uint8Array
}

export class ClientboundDebugEventPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundDebugEventPacket, {
		event: codec({
			encode(writer, value) {
				Codecs.varIntEnum(DebugSubscription).encode(writer, value.subscription)
				writer.writeBytes(value.payload)
			},
			decode(reader) {
				return {
					subscription: Codecs.varIntEnum(DebugSubscription).decode(reader),
					payload: reader.readRemaining(),
				}
			}
		})
	});

	constructor(
		public event: DebugEventPayload,
	) {
		super();
	}
}