// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundDeleteChatPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundDeleteChatPacket, {
		messageId: Codecs.varInt,
		signature: Codecs.conditionalOptional({
			valueCodec: Codecs.byteArray(256),
			shouldEncode: value => value != null,
			shouldDecode: reader => reader.remaining >= 256,
		}),
	});

	constructor(
		public messageId: number,
		public signature: Uint8Array | null
	) {
		super();
	}
}