// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundDisguisedChatPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundDisguisedChatPacket, {
		message: Codecs.nbt,
		chatType: Codecs.string(),
		senderName: Codecs.nbt,
		targetName: Codecs.prefixedOptional(Codecs.nbt),
	});

	constructor(
		public message: UnnamedNbtTag,
		public chatType: string,
		public senderName: UnnamedNbtTag,
		public targetName: UnnamedNbtTag | null
	) {
		super();
	}
}