// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundEntityEventPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundEntityEventPacket, {
		entityId: Codecs.int,
		eventId: Codecs.byte,
	});

	constructor(
		public entityId: number,
		public eventId: number
	) {
		super();
	}
}