// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { BlockPos } from '../../datatypes/BlockPos';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundGameTestHighlightPosPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundGameTestHighlightPosPacket, {
absolutePosition: BlockPos.codec,
relativePosition: BlockPos.codec,
	});

	constructor(
public absolutePosition: BlockPos,
public relativePosition: BlockPos
	) {
		super();
	}
}