// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { CommonPlayerSpawnInfo } from '../../datatypes/CommonPlayerSpawnInfo';
import type { Identifier } from '@dripleaf/registry';

export class ClientboundLoginPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundLoginPacket, {
		entityId: Codecs.int,
		isHardcore: Codecs.bool,
		dimensions: Codecs.array(Codecs.identifier),
		maxPlayers: Codecs.varInt,
		viewDistance: Codecs.varInt,
		simulationDistance: Codecs.varInt,
		reducedDebugInfo: Codecs.bool,
		enableRespawnScreen: Codecs.bool,
		doLimitedCrafting: Codecs.bool,
		commonPlayerSpawnInfo: CommonPlayerSpawnInfo.codec,
		enforcesSecureChat: Codecs.bool,
	});

	constructor(
		public entityId: number,
		public isHardcore: boolean,
		public dimensions: Identifier[],
		public maxPlayers: number,
		public viewDistance: number,
		public simulationDistance: number,
		public reducedDebugInfo: boolean,
		public enableRespawnScreen: boolean,
		public doLimitedCrafting: boolean,
		public commonPlayerSpawnInfo: CommonPlayerSpawnInfo,
		public portalCooldown: number,
		public seaLevel: number,
		public enforcesSecureChat: boolean
	) {
		super();
	}

}
