// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundMoveEntityPosPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundMoveEntityPosPacket, {
		entityId: Codecs.varInt,
		deltaX: Codecs.short,
		deltaY: Codecs.short,
		deltaZ: Codecs.short,
		onGround: Codecs.bool,
	});

	constructor(
		public entityId: number,
		public deltaX: number,
		public deltaY: number,
		public deltaZ: number,
		public onGround: boolean
	) {
		super();
	}
}