// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export class ClientboundMoveVehiclePacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundMoveVehiclePacket, {
		position: Codecs.vec3d,
		yaw: Codecs.float,
		pitch: Codecs.float,
	});

	constructor(
		public position: Vec3,
		public yaw: number,
		public pitch: number,
	) {
		super();
	}
}