// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundMoveEntityRotPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundMoveEntityRotPacket, {
		entityId: Codecs.varInt,
		yaw: Codecs.byte,
		pitch: Codecs.byte,
		onGround: Codecs.bool,
	});

	constructor(
		public entityId: number,
		public yaw: number,
		public pitch: number,
		public onGround: boolean
	) {
		super();
	}
}