// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { MenuType } from '@dripleaf/registry';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundOpenScreenPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundOpenScreenPacket, {
		containerId: Codecs.varInt,
		type: Codecs.varIntEnum(MenuType),
		title: Codecs.nbt,
	});

	constructor(
		public containerId: number,
		public type: MenuType,
		public title: UnnamedNbtTag
	) {
		super();
	}
}