// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundPlayerRotationPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundPlayerRotationPacket, {
		yaw: Codecs.float,
		relativeYaw: Codecs.bool,
		pitch: Codecs.float,
		relativePitch: Codecs.bool,
	});

	constructor(
		public yaw: number,
		public relativeYaw: boolean,
		public pitch: number,
		public relativePitch: boolean
	) {
		super();
	}
}