// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundPlayerCombatKillPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundPlayerCombatKillPacket, {
		playerId: Codecs.varInt,
		message: Codecs.nbt,
	});

	constructor(
		public playerId: number,
		public message: UnnamedNbtTag
	) {
		super();
	}
}