// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs, type PacketReader, type PacketWriter } from '../../buffer'
import { EntityAnchor } from '../../types'
import { DripleafPacket, packetCodec } from '../DripleafPacket'

export class ClientboundPlayerLookAtPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ClientboundPlayerLookAtPacket) {
			Codecs.varIntEnum(EntityAnchor).encode(writer, value.fromAnchor)
			writer.writeDouble(value.x)
			writer.writeDouble(value.y)
			writer.writeDouble(value.z)
			writer.writeBoolean(value.atEntity)
			if (value.atEntity) {
				if (value.entity == null || value.toAnchor == null) throw new Error('PlayerLookAtPacket atEntity requires entity and toAnchor')
				writer.writeVarInt(value.entity)
				Codecs.varIntEnum(EntityAnchor).encode(writer, value.toAnchor)
			}
		},
		decode(reader: PacketReader): ClientboundPlayerLookAtPacket {
			const fromAnchor = Codecs.varIntEnum(EntityAnchor).decode(reader)
			const x = reader.readDouble()
			const y = reader.readDouble()
			const z = reader.readDouble()
			const atEntity = reader.readBoolean()
			if (!atEntity)
				return new ClientboundPlayerLookAtPacket(fromAnchor, x, y, z, false, null, null)

			return new ClientboundPlayerLookAtPacket(
				fromAnchor,
				x,
				y,
				z,
				true,
				reader.readVarInt(),
				Codecs.varIntEnum(EntityAnchor).decode(reader),
			)
		},
	})

	constructor(
		public fromAnchor: EntityAnchor,
		public x: number,
		public y: number,
		public z: number,
		public atEntity: boolean,
		public entity: number | null,
		public toAnchor: EntityAnchor | null,
	) {
		super()
	}
}