// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundResourcePackPushPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundResourcePackPushPacket, {
		id: Codecs.uuid,
		url: Codecs.string(),
		hash: Codecs.string(),
		required: Codecs.bool,
		prompt: Codecs.prefixedOptional(Codecs.nbt)
	});

	constructor(
		public id: string,
		public url: string,
		public hash: string,
		public required: boolean,
		public prompt: UnnamedNbtTag | null,
	) {
		super();
	}
}