// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import type { UUID } from 'node:crypto';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundResourcePackPopPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundResourcePackPopPacket, {
		id: Codecs.prefixedOptional(Codecs.uuid)
	});


	constructor(
		public id: UUID | null,
	) {
		super();
	}
}