// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export type RecipeBookEntry = {
	contents: UnnamedNbtTag;
	flags: number;
};

function encodeEntry(writer: PacketWriter, entry: RecipeBookEntry) {
	writer.writeNbt(entry.contents);
	writer.writeByte(entry.flags);
}

function decodeEntry(reader: PacketReader): RecipeBookEntry {
	return {
		contents: reader.readNbt(),
		flags: reader.readByte(),
	};
}

export class ClientboundRecipeBookAddPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ClientboundRecipeBookAddPacket) {
			writer.writeArray(value.entries, entry => encodeEntry(writer, entry));
			writer.writeBoolean(value.replace);
		},
		decode(reader: PacketReader): ClientboundRecipeBookAddPacket {
			const entries = reader.readArray(() => decodeEntry(reader));
			const replace = reader.readBoolean();
			return new ClientboundRecipeBookAddPacket(entries, replace);
		},
	});

	constructor(
		public entries: RecipeBookEntry[],
		public replace: boolean,
	) {
		super();
	}
}
