// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export type NumberFormat =
	| { kind: "blank" }
	| { kind: "styled"; style: UnnamedNbtTag }
	| { kind: "fixed"; component: UnnamedNbtTag };

export function encodeNumberFormat(writer: PacketWriter, nf: NumberFormat | null) {
	writer.writeBoolean(nf != null);
	if (nf == null) return;
	switch (nf.kind) {
		case "blank":
			writer.writeVarInt(0);
			break;
		case "styled":
			writer.writeVarInt(1);
			writer.writeNbt(nf.style);
			break;
		case "fixed":
			writer.writeVarInt(2);
			writer.writeNbt(nf.component);
			break;
	}
}

export function decodeNumberFormat(reader: PacketReader): NumberFormat | null {
	if (!reader.readBoolean()) return null;
	const kind = reader.readVarInt();
	switch (kind) {
		case 0: return { kind: "blank" };
		case 1: return { kind: "styled", style: reader.readNbt() };
		case 2: return { kind: "fixed", component: reader.readNbt() };
		default: throw new Error(`Unknown number format type: ${kind}`);
	}
}

export class ClientboundSetObjectivePacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ClientboundSetObjectivePacket) {
			writer.writeString(value.objectiveName);
			writer.writeByte(value.method);
			if (value.method === 0 || value.method === 2) {
				writer.writeNbt(value.displayName!);
				writer.writeVarInt(value.renderType!);
				encodeNumberFormat(writer, value.numberFormat ?? null);
			}
		},
		decode(reader: PacketReader): ClientboundSetObjectivePacket {
			const objectiveName = reader.readString();
			const method = reader.readByte();
			let displayName: UnnamedNbtTag | undefined;
			let renderType: number | undefined;
			let numberFormat: NumberFormat | null | undefined;
			if (method === 0 || method === 2) {
				displayName = reader.readNbt();
				renderType = reader.readVarInt();
				numberFormat = decodeNumberFormat(reader);
			}
			return new ClientboundSetObjectivePacket(objectiveName, method, displayName, renderType, numberFormat);
		},
	});

	constructor(
		public objectiveName: string,
		public method: number,
		public displayName?: UnnamedNbtTag,
		public renderType?: number,
		public numberFormat?: NumberFormat | null,
	) {
		super();
	}
}
