// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundSetBorderWarningDistancePacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSetBorderWarningDistancePacket, {
		warningBlocks: Codecs.varInt,
	});

	constructor(
		public warningBlocks: number
	) {
		super();
	}
}