// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';
import { type NumberFormat, encodeNumberFormat, decodeNumberFormat } from './c_set_objective_packet';

export class ClientboundSetScorePacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ClientboundSetScorePacket) {
			writer.writeString(value.owner)
			writer.writeString(value.objectiveName)
			writer.writeVarInt(value.score)
			writer.writePrefixedOptional(value.display, display => writer.writeNbt(display))
			encodeNumberFormat(writer, value.numberFormat)
		},
		decode(reader: PacketReader): ClientboundSetScorePacket {
			return new ClientboundSetScorePacket(
				reader.readString(),
				reader.readString(),
				reader.readVarInt(),
				reader.readPrefixedOptional(() => reader.readNbt() as UnnamedNbtTag),
				decodeNumberFormat(reader),
			)
		},
	});

	constructor(
		public owner: string,
		public objectiveName: string,
		public score: number,
		public display: UnnamedNbtTag | null,
		public numberFormat: NumberFormat | null,
	) {
		super();
	}
}
