// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export class ClientboundSetEntityMotionPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSetEntityMotionPacket, {
		entityId: Codecs.varInt,
		movement: Codecs.lpVec3,
	});

	constructor(
		public entityId: number,
		public movement: Vec3
	) {
		super();
	}
}