// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import type { ItemStack } from '@dripleaf/inventory';
import { ItemStackCodec } from '../common';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundSetCursorItemPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSetCursorItemPacket, {
		contents: ItemStackCodec,
	});

	constructor(
		public contents: ItemStack,
	) {
		super();
	}
}