// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundServerDataPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundServerDataPacket, {
		motd: Codecs.nbt,
		iconBytes: Codecs.prefixedOptional(Codecs.byteArray())
	});

	constructor(
		public motd: UnnamedNbtTag,
		public iconBytes: Uint8Array | null	
	) {
		super();
	}
}