// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { RespawnData } from '../../datatypes/RespawnData';

export class ClientboundSetDefaultSpawnPositionPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSetDefaultSpawnPositionPacket, {
		respawnData: RespawnData.codec
	});

	constructor(
		public respawnData: RespawnData
	) {
		super();
	}
}