// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import type { Identifier } from '@dripleaf/registry';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundSelectAdvancementsTabPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSelectAdvancementsTabPacket, {
		tab: Codecs.prefixedOptional(Codecs.identifier)
	});

	constructor(
		public tab: Identifier | null
	) {
		super();
	}
}