// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundSetExperiencePacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSetExperiencePacket, {
		experienceProgress: Codecs.float,
		experienceLevel: Codecs.varInt,
		totalExperience: Codecs.varInt,
	});

	constructor(
		public experienceProgress: number,
		public totalExperience: number,
		public experienceLevel: number
	) {
		super();
	}
}