// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export type BlockChangeData = {
	position: number;
	blockStateId: number;
};

export class ClientboundSectionBlocksUpdatePacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ClientboundSectionBlocksUpdatePacket) {
			writer.writeVarInt(value.sectionX);
			writer.writeVarInt(value.sectionY);
			writer.writeVarInt(value.sectionZ);
			writer.writeVarInt(value.blocks.length);
			for (const block of value.blocks)
				writer.writeVarLong((BigInt(block.blockStateId) << 12n) | BigInt(block.position & 0xfff));
		},
		decode(reader: PacketReader): ClientboundSectionBlocksUpdatePacket {
			const sectionX = reader.readVarInt();
			const sectionY = reader.readVarInt();
			const sectionZ = reader.readVarInt();
			const count = reader.readVarInt();
			const blocks: BlockChangeData[] = [];
			for (let i = 0; i < count; i++) {
				const packed = reader.readVarLong();
				blocks.push({ position: Number(packed & 4095n), blockStateId: Number(packed >> 12n) });
			}
			return new ClientboundSectionBlocksUpdatePacket(sectionX, sectionY, sectionZ, blocks);
		},
	});

	constructor(
		public sectionX: number,
		public sectionY: number,
		public sectionZ: number,
		public blocks: BlockChangeData[],
	) {
		super();
	}

}
