// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer'
import { DripleafPacket, packetCodec } from '../DripleafPacket'

export enum DisplaySlot {
	List = 0,
	Sidebar = 1,
	BelowName = 2,
	TeamBlack = 3,
	TeamDarkBlue = 4,
	TeamDarkGreen = 5,
	TeamDarkAqua = 6,
	TeamDarkRed = 7,
	TeamDarkPurple = 8,
	TeamGold = 9,
	TeamGray = 10,
	TeamDarkGray = 11,
	TeamBlue = 12,
	TeamGreen = 13,
	TeamAqua = 14,
	TeamRed = 15,
	TeamLightPurple = 16,
	TeamYellow = 17,
	TeamWhite = 18,
}

export class ClientboundSetDisplayObjectivePacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSetDisplayObjectivePacket, {
		displaySlot: Codecs.varIntEnum(DisplaySlot),
		objectiveName: Codecs.string(),
	});

	constructor(
		public displaySlot: DisplaySlot,
		public objectiveName: string,
	) {
		super()
	}
}