// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundSetScorePacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSetScorePacket, {
		owner: Codecs.string(),
		objectiveName: Codecs.string(),
		score: Codecs.varInt,
		display: Codecs.prefixedOptional(Codecs.nbt),
		numberFormat: Codecs.prefixedOptional(Codecs.nbt),
	});

	constructor(
		public owner: string,
		public objectiveName: string,
		public score: number,
		public display: UnnamedNbtTag | null,
		public numberFormat: unknown | null,
	) {
		super();
	}
}