// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import type { SoundEvent } from '@dripleaf/registry';
import { Codecs, type Holder } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { SoundSource } from '../common';
import { soundHolderCodec } from 'src/datatypes';

export class ClientboundSoundPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSoundPacket, {
		sound: soundHolderCodec,
		source: Codecs.varIntEnum(SoundSource),
		x: Codecs.int,
		y: Codecs.int,
		z: Codecs.int,
		volume: Codecs.float,
		pitch: Codecs.float,
		seed: Codecs.long
	});

	constructor(
		sound: Holder<SoundEvent>,
		source: SoundSource,
		x: number,
		y: number,
		z: number,
		volume: number,
		pitch: number,
		seed: bigint
	) {
		super();
	}
}