// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import type { SoundEvent } from '@dripleaf/registry';
import { Codecs, type Holder } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { soundHolderCodec } from 'src';
import { SoundSource } from '../common';

export class ClientboundSoundEntityPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundSoundEntityPacket, {
		sound: soundHolderCodec,
		source: Codecs.varIntEnum(SoundSource),
		id: Codecs.int,
		volume: Codecs.float,
		pitch: Codecs.float,
		seed: Codecs.long
	})

	constructor(
		sound: Holder<SoundEvent>,
		source: SoundSource,
		id: number,
		volume: number,
		pitch: number,
		seed: bigint
	) {
		super();
	}
}