// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundTabListPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundTabListPacket, {
		header: Codecs.nbt,
		footer: Codecs.nbt,
	});

	constructor(
		public header: object,
		public footer: object,
	) {
		super();
	}

}
