// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundTakeItemEntityPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundTakeItemEntityPacket, {
		itemId: Codecs.varInt,
		playerId: Codecs.varInt,
		amount: Codecs.varInt
	});

	constructor(
		public itemId: number,
		public playerId: number,
		public amount: number,
	) {
		super();
	}
}