// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import type { UnnamedNbtTag } from '@dripleaf/nbt';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundTagQueryPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundTagQueryPacket, {
		transactionId: Codecs.varInt,
		tag: Codecs.nbt
	});

	constructor(
		public transactionId: number,
		public tag: UnnamedNbtTag | null,
	) {
		super();
	}
}