// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundTickingStatePacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundTickingStatePacket, {
		tickRate: Codecs.float,
		isFrozen: Codecs.bool
	});

	constructor(
		public tickRate: number,
		public isFrozen: boolean,
	) {
		super();
	}
}