// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from 'src/buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ClientboundUpdateMobEffectPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundUpdateMobEffectPacket, {
		entityId: Codecs.varInt,
		effect: Codecs.byteArray(), // todo: MobEffect
		effectAmplifier: Codecs.varInt,
		effectDurationTicks: Codecs.varInt,
		flags: Codecs.byte // todo: technically right but i want a bitfield type of datatype
	});

	constructor(
		public entityId: number,
		public effect: unknown, // todo: MobEffect
		public effectAmplifier: number,
		public effectDurationTicks: number,
		public flags: unknown // todo: bitfield: isAmbient, isVisible, showIcon, blend
	) {
		super();
	}
}