// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export class ServerboundBlockEntityTagQueryPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundBlockEntityTagQueryPacket, {
		transactionId: Codecs.varInt,
		pos: Codecs.blockPos,
	});

	constructor(
		public transactionId: number,
		public pos: Vec3,
	) {
		super();
	}

}
