// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundBundleItemSelectedPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundBundleItemSelectedPacket, {
		slotId: Codecs.varInt,
		selectedItemIndex: Codecs.varInt,
	});

	constructor(
		public slotId: number,
		public selectedItemIndex: number,
	) {
		super();
		if (selectedItemIndex < 0 && selectedItemIndex !== -1)
			throw new Error(`Invalid selectedItemIndex: ${selectedItemIndex}`);
	}

}
