// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

interface Instant {
	seconds: bigint;
	nanos: number;
}

interface LastSeenMessagesUpdate {
	offset: number;
	acknowledged: Uint8Array;
}

interface ArgumentSignature {
	name: string;
	signature: Uint8Array;
}

export class ServerboundChatCommandSignedPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ServerboundChatCommandSignedPacket) {
			writer.writeString(value.command);
			writer.writeLong(value.timestamp.seconds);
			writer.writeVarInt(value.timestamp.nanos);
			writer.writeLong(value.salt);
			writer.writeArray(value.argumentSignatures, entry => {
				writer.writeString(entry.name);
				writer.writeByteArray(entry.signature);
			});
			writer.writeVarInt(value.lastSeenMessages.offset);
			writer.writeFixedBitSet(value.lastSeenMessages.acknowledged, 20);
		},
		decode(reader: PacketReader): ServerboundChatCommandSignedPacket {
			return new ServerboundChatCommandSignedPacket(
				reader.readString(),
				{
					seconds: reader.readLong(),
					nanos: reader.readVarInt(),
				},
				reader.readLong(),
				reader.readArray(() => ({
					name: reader.readString(),
					signature: reader.readByteArray(),
				})),
				{
					offset: reader.readVarInt(),
					acknowledged: reader.readFixedBitSet(20),
				},
			);
		},
	});

	constructor(
		public command: string,
		public timestamp: Instant,
		public salt: bigint,
		public argumentSignatures: ArgumentSignature[],
		public lastSeenMessages: LastSeenMessagesUpdate,
	) {
		super();
	}

}
