// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { GameType } from '../../datatypes/GameType';

export class ServerboundChangeGameModePacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundChangeGameModePacket, {
		mode: Codecs.varIntEnum<GameType>(),
	});

	constructor(
		public mode: GameType,
	) {
		super();
	}

}
