// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs, type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

interface Instant {
	seconds: bigint;
	nanos: number;
}

interface LastSeenMessagesUpdate {
	offset: number;
	acknowledged: Uint8Array;
}

export class ServerboundChatPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ServerboundChatPacket) {
			writer.writeString(value.message, 256);
			writer.writeLong(value.timestamp.seconds);
			writer.writeVarInt(value.timestamp.nanos);
			writer.writeLong(value.salt);
			writer.writePrefixedOptional(value.signature, sig => writer.writeByteArray(sig));
			writer.writeVarInt(value.lastSeenMessages.offset);
			writer.writeFixedBitSet(value.lastSeenMessages.acknowledged, 20);
		},
		decode(reader: PacketReader): ServerboundChatPacket {
			return new ServerboundChatPacket(
				reader.readString(256),
				{
					seconds: reader.readLong(),
					nanos: reader.readVarInt(),
				},
				reader.readLong(),
				reader.readPrefixedOptional(() => reader.readByteArray()),
				{
					offset: reader.readVarInt(),
					acknowledged: reader.readFixedBitSet(20),
				},
			);
		},
	});

	constructor(
		public message: string,
		public timestamp: Instant,
		public salt: bigint,
		public signature: Uint8Array | null,
		public lastSeenMessages: LastSeenMessagesUpdate,
	) {
		super();
	}

}
