// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { UUID } from 'node:crypto';

interface Instant {
	seconds: bigint;
	nanos: number;
}

interface ProfilePublicKeyData {
	expiresAt: Instant;
	key: Uint8Array;
}

interface RemoteChatSessionData {
	sessionId: UUID;
	profileId: UUID;
	publicKey: ProfilePublicKeyData;
}

export class ServerboundChatSessionUpdatePacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ServerboundChatSessionUpdatePacket) {
			writer.writeUUID(value.chatSession.sessionId);
			writer.writeUUID(value.chatSession.profileId);
			writer.writeLong(value.chatSession.publicKey.expiresAt.seconds);
			writer.writeVarInt(value.chatSession.publicKey.expiresAt.nanos);
			writer.writeByteArray(value.chatSession.publicKey.key);
		},
		decode(reader: PacketReader): ServerboundChatSessionUpdatePacket {
			return new ServerboundChatSessionUpdatePacket({
				sessionId: reader.readUUID(),
				profileId: reader.readUUID(),
				publicKey: {
					expiresAt: {
						seconds: reader.readLong(),
						nanos: reader.readVarInt(),
					},
					key: reader.readByteArray(),
				},
			});
		},
	});

	constructor(
		public chatSession: RemoteChatSessionData,
	) {
		super();
	}

}
