// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export enum ClientCommandAction {
	PerformRespawn = 0,
	RequestStats = 1,
	RequestGameruleValues = 2,
}

export class ServerboundClientCommandPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundClientCommandPacket, {
		action: Codecs.varIntEnum<ClientCommandAction>(),
	});

	constructor(
		public action: ClientCommandAction,
	) {
		super();
	}

}
