// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundContainerSlotStateChangedPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundContainerSlotStateChangedPacket, {
		slotId: Codecs.varInt,
		containerId: Codecs.containerId,
		newState: Codecs.bool,
	});

	constructor(
		public slotId: number,
		public containerId: number,
		public newState: boolean,
	) {
		super();
	}

}
