// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import type { Identifier } from '@dripleaf/registry';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundCookieResponsePacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundCookieResponsePacket, {
		key: Codecs.identifier,
		payload: Codecs.prefixedOptional(Codecs.byteArray(5120))
	});

	constructor(
		public key: Identifier,
		public payload: Uint8Array | null,
	) {
		super();
	}
}