// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import type { Identifier } from '@dripleaf/registry';
import type { UnnamedNbtTag } from '@dripleaf/nbt';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundCustomClickActionPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundCustomClickActionPacket, {
		id: Codecs.identifier,
		payload: Codecs.nbt,
	});

	constructor(
		public id: Identifier,
		public payload: UnnamedNbtTag,
	) {
		super();
	}
}