// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import type { Identifier } from '@dripleaf/registry';
import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundCustomPayloadPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundCustomPayloadPacket, {
		identifier: Codecs.identifier,
		data: Codecs.byteArray(),
	});

	constructor(
		public identifier: Identifier,
		public data: Uint8Array,
	) {
		super();
	}
}