// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { InteractionHand } from '../../types';
import { Codecs, type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export type InteractAction =
	| { kind: "interact"; hand: InteractionHand }
	| { kind: "interactAt"; hand: InteractionHand; location: Vec3 };

export class ServerboundInteractPacket extends DripleafPacket {
	static readonly codec = packetCodec({
		encode(writer: PacketWriter, value: ServerboundInteractPacket) {
			writer.writeVarInt(value.entityId);
			switch (value.action.kind) {
				case "interact":
					writer.writeVarInt(0);
					Codecs.varIntEnum(InteractionHand).encode(writer, value.action.hand);
					break;
				case "interactAt":
					writer.writeVarInt(1);
					Codecs.varIntEnum(InteractionHand).encode(writer, value.action.hand);
					writer.writeLpVec3(value.action.location);
					break;
			}
			writer.writeBoolean(value.usingSecondaryAction);
		},
		decode(reader: PacketReader): ServerboundInteractPacket {
			const entityId = reader.readVarInt();
			const type = reader.readVarInt();
			let action: InteractAction;
			switch (type) {
				case 0:
					action = { kind: "interact", hand: Codecs.varIntEnum(InteractionHand).decode(reader) };
					break;
				case 1:
					action = { kind: "interactAt", hand: Codecs.varIntEnum(InteractionHand).decode(reader), location: reader.readLpVec3() };
					break;
				default:
					throw new Error(`Unknown interact type: ${type}`);
			}
			const usingSecondaryAction = reader.readBoolean();
			return new ServerboundInteractPacket(entityId, action, usingSecondaryAction);
		},
	});

	constructor(
		public entityId: number,
		public action: InteractAction,
		public usingSecondaryAction: boolean,
	) {
		super();
	}

}
