// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export class ServerboundJigsawGeneratePacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundJigsawGeneratePacket, {
		pos: Codecs.blockPos,
		levels: Codecs.varInt,
		keepJigsaws: Codecs.bool,
	});

	constructor(
		public pos: Vec3,
		public levels: number,
		public keepJigsaws: boolean,
	) {
		super();
	}

}
