// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export class ServerboundMoveVehiclePacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundMoveVehiclePacket, {
		position: Codecs.vec3d,
		yRot: Codecs.float,
		xRot: Codecs.float,
		onGround: Codecs.bool,
	});

	constructor(
		public position: Vec3,
		public yRot: number,
		public xRot: number,
		public onGround: boolean,
	) {
		super();
	}

}
