// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundPickItemFromEntityPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundPickItemFromEntityPacket, {
		id: Codecs.varInt,
		includeData: Codecs.bool,
	});

	constructor(
		public id: number,
		public includeData: boolean,
	) {
		super();
	}

}
