// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Vec3 } from 'vec3';

export class ServerboundPickItemFromBlockPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundPickItemFromBlockPacket, {
		pos: Codecs.blockPos,
		includeData: Codecs.bool,
	});

	constructor(
		public pos: Vec3,
		public includeData: boolean,
	) {
		super();
	}

}
