// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export enum PlayerCommandAction {
	StopSleeping = 0,
	StartSprinting = 1,
	StopSprinting = 2,
	StartRidingJump = 3,
	StopRidingJump = 4,
	OpenInventory = 5,
	StartFallFlying = 6,
}

export class ServerboundPlayerCommandPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundPlayerCommandPacket, {
		id: Codecs.varInt,
		action: Codecs.varIntEnum<PlayerCommandAction>(),
		data: Codecs.varInt,
	});

	constructor(
		public id: number,
		public action: PlayerCommandAction,
		public data: number,
	) {
		super();
	}

}
