// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Identifier } from '@dripleaf/registry';

export class ServerboundPlaceRecipePacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundPlaceRecipePacket, {
		containerId: Codecs.varInt,
		recipe: Codecs.identifier,
		shiftDown: Codecs.bool,
	});

	constructor(
		public containerId: number,
		public recipe: Identifier,
		public shiftDown: boolean,
	) {
		super();
	}

}
