// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export enum RecipeBookType {
	Crafting = 0,
	Furnace = 1,
	BlastFurnace = 2,
	Smoker = 3,
}

export class ServerboundRecipeBookChangeSettingsPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundRecipeBookChangeSettingsPacket, {
		bookType: Codecs.varIntEnum(RecipeBookType),
		isOpen: Codecs.bool,
		isFiltering: Codecs.bool,
	});

	constructor(
		public bookType: RecipeBookType,
		public isOpen: boolean,
		public isFiltering: boolean,
	) {
		super();
	}
}