// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Identifier } from '@dripleaf/registry';

export class ServerboundRecipeBookSeenRecipePacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundRecipeBookSeenRecipePacket, {
		recipe: Codecs.identifier,
	});

	constructor(
		public recipe: Identifier,
	) {
		super();
	}
}