// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export enum ResourcePackAction {
	SuccessfullyLoaded = 0,
	Declined = 1,
	FailedDownload = 2,
	Accepted = 3,
	InvalidUrl = 4,
	FailedReload = 5,
	Discarded = 6,
}

export class ServerboundResourcePackPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundResourcePackPacket, {
		id: Codecs.uuid,
		action: Codecs.varIntEnum(ResourcePackAction),
	});

	constructor(
		public id: string,
		public action: ResourcePackAction,
	) {
		super();
	}
}