// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

export class ServerboundSelectTradePacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundSelectTradePacket, {
		item: Codecs.varInt,
	});

	constructor(
		public item: number,
	) {
		super();
	}

}
