// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { BlockPos } from '../../datatypes/BlockPos';

enum TestBlockMode {
	START,
	LOG,
	FAIL,
	ACCEPT,
}

export class ServerboundSetTestBlockPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundSetTestBlockPacket, {
		position: BlockPos.codec,
		mode: Codecs.varIntEnum(TestBlockMode),
		message: Codecs.string(),
	});

	constructor(
		public position: BlockPos,
		public mode: TestBlockMode,
		public message: string
	) {
		super();
	}

}
