// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs, type PacketReader, type PacketWriter } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import type { Identifier } from '@dripleaf/registry';

type GameRuleEntry = {
	name: Identifier;
	value: string;
};

export class ServerboundSetGameRulePacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundSetGameRulePacket, {
		entries: Codecs.array({
			encode(writer, value) {
				writer.writeIdentifier(value.name);
				writer.writeString(value.value);
			},
			decode(reader) {
				const name = reader.readIdentifier();
				const value = reader.readString();
				return { name, value };
			},
		}),
	});

	constructor(
		public entries: GameRuleEntry[]
	) {
		super();
	}
}