// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { InteractionHand } from '../../types';

export class ServerboundSwingPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundSwingPacket, {
		hand: Codecs.varIntEnum(InteractionHand),
	});

	constructor(
		public hand: InteractionHand,
	) {
		super();
	}
}