// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { InteractionHand } from '../../types';

export class ServerboundUseItemPacket extends DripleafPacket {
	static readonly codec = packetCodec(ServerboundUseItemPacket, {
		hand: Codecs.varIntEnum<InteractionHand>(),
		sequence: Codecs.varInt,
		yRot: Codecs.float,
		xRot: Codecs.float,
	});

	constructor(
		public hand: InteractionHand,
		public sequence: number,
		public yRot: number,
		public xRot: number,
	) {
		super();
	}

}
