// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

class ServerboundIntentionPacket extends GlowstonePacket {
	override id = 0x00;
	override state = State.Handshake;
	override direction = Direction.Serverbound;

	constructor(
		public protocolVersion: number,
		public serverAddress: string,
		public serverPort: number,
		public intention: number
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeVarInt(this.protocolVersion);
		writer.writeString(this.serverAddress, 255);
		writer.writeUnsignedShort(this.serverPort);
		writer.writeVarInt(this.intention);
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ServerboundIntentionPacket {
		const reader = new PacketReader(bytes);
		const protocolVersion = reader.readVarInt();
		const serverAddress = reader.readString(255);
		const serverPort = reader.readUnsignedShort();
		const intention = reader.readVarInt();
		return new ServerboundIntentionPacket(protocolVersion, serverAddress, serverPort, intention);
	}
}

export { ServerboundIntentionPacket };
