// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { codec, Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';

type DetailEntry = {
	title: string;
	description: string;
}

export class ClientboundCustomReportDetailsPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundCustomReportDetailsPacket, {
		details: Codecs.array<DetailEntry>(codec<DetailEntry>({
			encode(writer, value) {
				writer.writeString(value.title);
				writer.writeString(value.description);
			},
			decode(reader) {
				const title = reader.readString(128);
				const description = reader.readString(4096);
				return { title, description };
			}
		})),
	});

	constructor(
		public details: DetailEntry[],
	) {
		super();
	}
}