// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundResourcePackPushPacket extends DripleafPacket {
	static readonly id = 0x09;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundResourcePackPushPacket.id;
	override readonly state = ClientboundResourcePackPushPacket.state;
	override readonly direction = ClientboundResourcePackPushPacket.direction;

	constructor(
		public uuid: string,
		public url: string,
		public hash: string,
		public forced: boolean,
		public promptMessage: UnnamedNbtTag | null
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeUUID(this.uuid);
		writer.writeString(this.url);
		writer.writeString(this.hash);
		writer.writeBoolean(this.forced);
		writer.writePrefixedOptional(this.promptMessage, (value) => writer.writeNbt(value));
	}

	static read(reader: PacketReader): ClientboundResourcePackPushPacket {
		const uuid = reader.readUUID();
		const url = reader.readString();
		const hash = reader.readString();
		const forced = reader.readBoolean();
		const promptMessage = reader.readPrefixedOptional(() => reader.readNbt());
		return new ClientboundResourcePackPushPacket(uuid, url, hash, forced, promptMessage);
	}
}