// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { codec, Codecs } from '../../buffer';
import { DripleafPacket, packetCodec } from '../DripleafPacket';
import { ServerLinkType, type ServerLink } from '../common';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundServerLinksPacket extends DripleafPacket {
	static readonly codec = packetCodec(ClientboundServerLinksPacket, {
		links: Codecs.array<ServerLink>(codec({
			encode(writer, value) {
				writer.writeEither<ServerLinkType, UnnamedNbtTag>(
					value.label,
					(label) => writer.writeVarInt(label),
					(label) => writer.writeNbt(label)
				);
				writer.writeString(value.url);
			},
			decode(reader) {
				const label = reader.readEither<ServerLinkType, UnnamedNbtTag>(
					() => reader.readVarInt(),
					() => reader.readNbt()
				);
				const url = reader.readString(32767);
				return { label, url };
			}
		}))
	});

	constructor(
		public links: ServerLink[]
	) {
		super();
	}

}
