// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ClientboundShowDialogPacket extends DripleafPacket {
	static readonly id = 0x12;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Clientbound;

	override readonly id = ClientboundShowDialogPacket.id;
	override readonly state = ClientboundShowDialogPacket.state;
	override readonly direction = ClientboundShowDialogPacket.direction;

	constructor(
		public dialog: UnnamedNbtTag
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeNbt(this.dialog);
	}

	static read(reader: PacketReader): ClientboundShowDialogPacket {
		const dialog = reader.readNbt();
		return new ClientboundShowDialogPacket(dialog);
	}
}