// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import type { UnnamedNbtTag } from '@dripleaf/nbt';

export class ServerboundCustomClickActionPacket extends DripleafPacket {
	static readonly id = 0x08;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Serverbound;

	override readonly id = ServerboundCustomClickActionPacket.id;
	override readonly state = ServerboundCustomClickActionPacket.state;
	override readonly direction = ServerboundCustomClickActionPacket.direction;

	constructor(
		public identifier: string,
		public payload: UnnamedNbtTag
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeString(this.identifier);
		writer.writeNbt(this.payload);
	}

	static read(reader: PacketReader): ServerboundCustomClickActionPacket {
		const identifier = reader.readString();
		const payload = reader.readNbt();
		return new ServerboundCustomClickActionPacket(identifier, payload);
	}
}