// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { PacketReader, PacketWriter } from '../../buffer';
import { DripleafPacket } from '../DripleafPacket';
import { Direction, State } from '../../types';
import { KnownPack } from '../../datatypes/KnownPack';

export class ServerboundSelectKnownPacksPacket extends DripleafPacket {
	static readonly id = 0x07;
	static readonly state = State.Configuration;
	static readonly direction = Direction.Serverbound;

	override readonly id = ServerboundSelectKnownPacksPacket.id;
	override readonly state = ServerboundSelectKnownPacksPacket.state;
	override readonly direction = ServerboundSelectKnownPacksPacket.direction;

	constructor(
		public knownPacks: KnownPack[],
	) {
		super();
	}

	write(writer: PacketWriter) {
		writer.writeArray(this.knownPacks, (pack) => pack.write(writer));
	}

	static read(reader: PacketReader): ServerboundSelectKnownPacksPacket {
		const knownPacks = reader.readArray(() => KnownPack.read(reader));
		return new ServerboundSelectKnownPacksPacket(knownPacks);
	}
}