// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

class ClientboundCustomQueryPacket extends GlowstonePacket {
	override id = 0x04;
	override state = State.Login;
	override direction = Direction.Clientbound;

	constructor(
		public messageId: number,
		public channel: string,
		public data: Uint8Array
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeVarInt(this.messageId);
		writer.writeString(this.channel);
		writer.writeByteArray(this.data);
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ClientboundCustomQueryPacket {
		const reader = new PacketReader(bytes);
		const messageId = reader.readVarInt();
		const channel = reader.readString();
		const data = reader.readByteArray();
		return new ClientboundCustomQueryPacket(messageId, channel, data);
	}
}

export { ClientboundCustomQueryPacket };