// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State, type GameProfile } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

class ClientboundLoginFinishedPacket extends GlowstonePacket {
	override id = 0x02;
	override state = State.Login;
	override direction = Direction.Clientbound;

	constructor(
		public profile: GameProfile
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeUUID(this.profile.id);
		writer.writeString(this.profile.name);
		writer.writeVarInt(this.profile.properties.length);
		for (const property of this.profile.properties) {
			writer.writeString(property.name);
			writer.writeString(property.value);
			writer.writePrefixedOptional(property.signature, (signature) => writer.writeString(signature));
		}
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ClientboundLoginFinishedPacket {
		const reader = new PacketReader(bytes);
		const id = reader.readUUID();
		const name = reader.readString();
		const propertyCount = reader.readVarInt();
		const properties: { name: string; value: string; signature?: string | null }[] = [];
		for (let i = 0; i < propertyCount; i++) {
			const propertyName = reader.readString();
			const propertyValue = reader.readString();
			const signature = reader.readPrefixedOptional(() => reader.readString());
			properties.push({ name: propertyName, value: propertyValue, signature });
		}
		return new ClientboundLoginFinishedPacket({ id, name, properties });
	}
}

export { ClientboundLoginFinishedPacket };