// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

class ClientboundLoginDisconnectPacket extends GlowstonePacket {
	override id = 0x00;
	override state = State.Login;
	override direction = Direction.Clientbound;

	constructor(
		public reason: Object,
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeString(JSON.stringify(this.reason));
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ClientboundLoginDisconnectPacket {
		const reader = new PacketReader(bytes);
		const reason = JSON.parse(reader.readString());
		return new ClientboundLoginDisconnectPacket(reason);
	}
}

export { ClientboundLoginDisconnectPacket };