// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

class ClientboundLoginCompressionPacket extends GlowstonePacket {
	override id = 0x03;
	override state = State.Login;
	override direction = Direction.Clientbound;

	constructor(
		public threshold: number
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeVarInt(this.threshold);
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ClientboundLoginCompressionPacket {
		const reader = new PacketReader(bytes);
		const threshold = reader.readVarInt();
		return new ClientboundLoginCompressionPacket(threshold);
	}
}

export { ClientboundLoginCompressionPacket };