// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

class ServerboundCookieResponsePacket extends GlowstonePacket {
	override id = 0x04;
	override state = State.Login;
	override direction = Direction.Serverbound;

	constructor(
		public key: string,
		public payload?: Uint8Array | null
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeString(this.key);
		writer.writePrefixedOptional(this.payload, (v) => writer.writeByteArray(v));
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ServerboundCookieResponsePacket {
		const reader = new PacketReader(bytes);
		const key = reader.readString();
		const payload = reader.readPrefixedOptional(() => reader.readByteArray());
		return new ServerboundCookieResponsePacket(key, payload);
	}
}

export { ServerboundCookieResponsePacket };