// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';

class ServerboundCustomQueryAnswerPacket extends GlowstonePacket {
	override id = 0x02;
	override state = State.Login;
	override direction = Direction.Serverbound;

	constructor(
		public messageId: number,
		public response: Uint8Array
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeVarInt(this.messageId);
		writer.writeByteArray(this.response);
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ServerboundCustomQueryAnswerPacket {
		const reader = new PacketReader(bytes);
		const messageId = reader.readVarInt();
		const response = reader.readByteArray();
		return new ServerboundCustomQueryAnswerPacket(messageId, response);
	}
}

export { ServerboundCustomQueryAnswerPacket };