// This file is generated by codegen/generate_packets.ts. Do not edit this file manually unless you are Khao who always knows what he is doing.

import { Direction, State } from '../../types';
import { GlowstonePacket } from '../../packet';
import { PacketReader, PacketWriter } from '../../buffer';
import type { UUID } from 'node:crypto';

class ServerboundHelloPacket extends GlowstonePacket {
	override id = 0x00;
	override state = State.Login;
	override direction = Direction.Serverbound;

	constructor(
		public name: string,
		public uuid: UUID
	) {
		super();
	}

	serialize() {
		const writer = new PacketWriter();
		writer.writeString(this.name);
		writer.writeUUID(this.uuid);
		return writer.finish();
	}

	static override deserialize(bytes: Uint8Array): ServerboundHelloPacket {
		const reader = new PacketReader(bytes);
		const name = reader.readString();
		const uuid = reader.readUUID();
		return new ServerboundHelloPacket(name, uuid);
	}
}

export { ServerboundHelloPacket };